---
- name: "Uninstall Server"
  ansible.builtin.import_tasks: uninstall/uninstall_server.yml
  when:
    - velociraptor_server|bool
  tags:
    - never
    - uninstall_server

- name: "Uninstall Linux Client"
  ansible.builtin.import_tasks: uninstall/uninstall_linux_client.yml
  when:
    - velociraptor_client|bool
    - ansible_os_family != "Windows"
    - ansible_os_family != "Darwin"
  tags:
    - never
    - uninstall_client

- name: "Uninstall MacOS Client"
  ansible.builtin.import_tasks: uninstall/uninstall_mac_client.yml
  when:
    - velociraptor_client|bool
    - ansible_os_family == "Darwin"
  tags:
    - never
    - uninstall_client

- name: "Uninstall Windows Client"
  ansible.builtin.import_tasks: uninstall/uninstall_windows_client.yml
  when:
    - velociraptor_client|bool
    - ansible_os_family == "Windows"
  tags:
    - never
    - uninstall_client
